namespace Interpreter.Grammar
{
    public enum TokenType
    {
        ID,
        CONST,
        ASSIGN,
        SEMICOLON,
        COLON,
        PLUS,
        MINUS,
        MULT,
        OPENPAREN,
        CLOSEPAREN,
        WHILE,
        DO,
        END,
        AND,
        OR,
        REL,
        CLOSEBRACE,
        OPENBRACE,
        INCREMENT,
        FOR,
        LOOP,
        UNTIL,
        DIV
    }
}
